apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: oyinyecouture
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: frontend
