
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
      DATABASE_URL: ${DATABASE_URL}
      IPINFO_TOKEN: ${IPINFO_TOKEN}
      NEXT_PUBLIC_MER_CODE: ${NEXT_PUBLIC_MER_CODE}
      NEXT_PUBLIC_PAY_ITEM_ID: ${NEXT_PUBLIC_PAY_ITEM_ID}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

