
services:
  oyinye-web:
    image: je278/oyinye:1.0
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN: ${DOMAIN}
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
      MONGO_URI: ${MONGO_URI}
      DATABASE_URL: ${DATABASE_URL}
      IPINFO_TOKEN: ${IPINFO_TOKEN}
      NEXT_PUBLIC_MER_CODE: ${NEXT_PUBLIC_MER_CODE}
      NEXT_PUBLIC_PAY_ITEM_ID: ${NEXT_PUBLIC_PAY_ITEM_ID}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}


