apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oyinyecouture-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    # - host: oyinye.com
     - http:
        paths:
            - path: /api/auth
              pathType: Prefix
              backend:
                service:
                  name: auth-service
                  port:
                    number: 8000
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: web-service
                  port:
                    number: 4000
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: admin-service
                  port:
                    number: 8080
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: frontend-service
                  port:
                    number: 3000